from pubnub.pnconfiguration import PNConfiguration
from pubnub.pubnub import PubNub
from pubnub.callbacks import SubscribeCallback
import key
import random 

print(random.random())
pnconfig = PNConfiguration()
pnconfig.publish_key = key.publish
pnconfig.subscribe_key = key.subscribe

pnconfig.uuid = input("Enter username: ").strip()

token_str = input("Paste the token generated by GP.py (for this exact username): ").strip()

pubnub = PubNub(pnconfig)

pubnub.set_token(token_str)

CHANNEL = "blackpearl"

class MySubscribeCallback(SubscribeCallback):
    def message(self, pubnub, message):
        data = message.message
        print(f"\n{data['user']}: {data['text']}")

    def status(self, pubnub, status):
        print("STATUS:", status.category)

pubnub.add_listener(MySubscribeCallback())
pubnub.subscribe().channels(CHANNEL).execute()

print("✅ Connected! Start chatting:\n")

while True:
    try:
        msg = input("> ")
        pubnub.publish().channel(CHANNEL).message({
            "user": pnconfig.user_id,      
            "text": msg
        }).sync()
    except Exception as e:
        print("Error:", e)